<?php

return [
    'groups' => [
        'Dashboard' => [
            'dashboard.view' => 'View dashboard',
            'dashboard.widgets.view' => 'View dashboard widget catalog',
            'dashboard.widgets.manage' => 'Manage dashboard widgets',
        ],
        'Catalog' => [
            'products.view' => 'View products',
            'products.manage' => 'Manage products',
            'categories.view' => 'View categories',
            'categories.manage' => 'Manage categories',
            'brands.view' => 'View brands',
            'brands.manage' => 'Manage brands',
            'collections.view' => 'View collections',
            'collections.manage' => 'Manage collections',
        ],
        'Inventory' => [
            'inventory.view' => 'View inventory',
            'inventory.manage' => 'Manage inventory',
            'warehouses.view' => 'View warehouses',
            'warehouses.manage' => 'Manage warehouses',
        ],
        'Commerce' => [
            'orders.view' => 'View orders',
            'orders.manage' => 'Manage orders',
        ],
        'Marketing' => [
            'offers.view' => 'View offers',
            'offers.manage' => 'Manage offers',
            'discounts.view' => 'View discounts',
            'discounts.manage' => 'Manage discounts',
            'sale-products.view' => 'View sale products',
            'sale-products.manage' => 'Manage sale products',
            'promotions.view' => 'View promotions',
            'promotions.manage' => 'Manage promotions',
        ],
        'Customers' => [
            'customers.view' => 'View customers',
            'customers.manage' => 'Manage customers',
        ],
        'Content' => [
            'media.view' => 'View media library',
            'media.manage' => 'Upload and manage media',
            'media.folders.manage' => 'Manage media folders',
            'homepage.view' => 'View homepage content',
            'homepage.manage' => 'Manage homepage content',
        ],
        'Administration' => [
            'settings.view' => 'View store settings',
            'settings.manage' => 'Manage store settings',
            'notifications.view' => 'View notifications',
            'notifications.manage' => 'Manage notification broadcasts',
            'audit.view' => 'View audit logs',
            'users.view' => 'View admin users',
            'users.manage' => 'Manage admin users',
            'roles.view' => 'View roles',
            'roles.manage' => 'Manage roles',
            'permissions.view' => 'View permissions',
            'permissions.manage' => 'Manage permissions',
            'access-matrix.manage' => 'Manage permission matrix',
        ],
    ],

    'roles' => [
        'owner' => [
            'name' => 'Owner',
            'description' => 'Full platform access including administration and security settings.',
        ],
        'manager' => [
            'name' => 'Manager',
            'description' => 'Operational oversight across catalog, inventory, orders, and customers.',
        ],
        'product_manager' => [
            'name' => 'Product Manager',
            'description' => 'Manage catalog content including products, categories, and brands.',
        ],
        'inventory_manager' => [
            'name' => 'Inventory Manager',
            'description' => 'Manage stock levels, warehouses, and inventory movements.',
        ],
        'order_manager' => [
            'name' => 'Order Manager',
            'description' => 'Manage order lifecycle, fulfillment status, and order notes.',
        ],
        'customer_support' => [
            'name' => 'Customer Support',
            'description' => 'Support customers with profile access, notes, and order visibility.',
        ],
        'marketing_manager' => [
            'name' => 'Marketing Manager',
            'description' => 'Manage offers, discounts, promotions, and marketing campaigns.',
        ],
    ],

    'role_permissions' => [
        'owner' => '*',
        'manager' => [
            'dashboard.view',
            'products.view',
            'products.manage',
            'categories.view',
            'categories.manage',
            'brands.view',
            'brands.manage',
            'collections.view',
            'collections.manage',
            'inventory.view',
            'inventory.manage',
            'orders.view',
            'orders.manage',
            'customers.view',
            'customers.manage',
            'offers.view',
            'offers.manage',
            'discounts.view',
            'discounts.manage',
            'sale-products.view',
            'sale-products.manage',
            'promotions.view',
            'promotions.manage',
            'homepage.view',
            'homepage.manage',
            'settings.view',
            'media.view',
            'media.manage',
            'media.folders.manage',
            'notifications.view',
            'audit.view',
            'roles.view',
            'permissions.view',
            'dashboard.widgets.view',
            'dashboard.widgets.manage',
        ],
        'product_manager' => [
            'dashboard.view',
            'products.view',
            'products.manage',
            'categories.view',
            'categories.manage',
            'brands.view',
            'brands.manage',
            'collections.view',
            'collections.manage',
            'inventory.view',
            'offers.view',
            'offers.manage',
            'discounts.view',
            'sale-products.view',
            'promotions.view',
            'homepage.view',
            'homepage.manage',
            'media.view',
            'media.manage',
        ],
        'inventory_manager' => [
            'dashboard.view',
            'products.view',
            'inventory.view',
            'inventory.manage',
            'warehouses.view',
            'warehouses.manage',
            'notifications.view',
        ],
        'order_manager' => [
            'dashboard.view',
            'orders.view',
            'orders.manage',
            'customers.view',
            'notifications.view',
        ],
        'customer_support' => [
            'dashboard.view',
            'customers.view',
            'customers.manage',
            'orders.view',
            'notifications.view',
        ],
        'marketing_manager' => [
            'dashboard.view',
            'offers.view',
            'offers.manage',
            'discounts.view',
            'discounts.manage',
            'sale-products.view',
            'sale-products.manage',
            'promotions.view',
            'promotions.manage',
            'collections.view',
            'customers.view',
            'homepage.view',
            'notifications.view',
        ],
    ],

    'default_users' => [
        [
            'name' => 'Jordan Reeves',
            'email' => 'owner@valorsupply.co',
            'role' => 'owner',
        ],
        [
            'name' => 'Alex Morgan',
            'email' => 'manager@valorsupply.co',
            'role' => 'manager',
        ],
        [
            'name' => 'Sam Ortiz',
            'email' => 'product@valorsupply.co',
            'role' => 'product_manager',
        ],
        [
            'name' => 'Riley Chen',
            'email' => 'inventory@valorsupply.co',
            'role' => 'inventory_manager',
        ],
        [
            'name' => 'Casey Brooks',
            'email' => 'orders@valorsupply.co',
            'role' => 'order_manager',
        ],
        [
            'name' => 'Taylor Reed',
            'email' => 'support@valorsupply.co',
            'role' => 'customer_support',
        ],
        [
            'name' => 'Morgan Vale',
            'email' => 'marketing@valorsupply.co',
            'role' => 'marketing_manager',
        ],
    ],
];
