<?php

use App\Enums\Admin\DashboardWidgetType;

return [

    /*
    |--------------------------------------------------------------------------
    | Cache
    |--------------------------------------------------------------------------
    | TTL (seconds) applied to computed widget payloads. Set to 0 to disable
    | caching globally. Individual widget providers may override this.
    */
    'cache_ttl' => (int) env('DASHBOARD_CACHE_TTL', 300),

    'cache_prefix' => 'admin:dashboard',

    /*
    |--------------------------------------------------------------------------
    | Responsive grid
    |--------------------------------------------------------------------------
    | The dashboard renders on a 12-column grid. A widget "width" is expressed
    | in grid columns (1-12) and is clamped to these bounds.
    */
    'grid_columns' => 12,
    'min_width' => 3,
    'max_width' => 12,

    /*
    |--------------------------------------------------------------------------
    | Default global date range
    |--------------------------------------------------------------------------
    */
    'default_range' => 'last_30_days',

    /*
    |--------------------------------------------------------------------------
    | Widget catalog
    |--------------------------------------------------------------------------
    | Source of truth used by DashboardWidgetSeeder to populate the
    | `dashboard_widgets` table. Admins can override any of these at runtime
    | through the Widget Management module; the seeder only creates missing
    | rows (it never overwrites admin edits).
    |
    | width: grid columns (3-12) · roles: [] means "all roles (subject to
    | permission)" · permission: null means "any dashboard user".
    */
    'widgets' => [
        // ---- Business summary / statistic cards ----------------------------
        [
            'key' => 'sales-stats',
            'name' => "Today's Performance",
            'description' => 'Sales, orders, revenue and average order value for the selected range.',
            'icon' => 'M3 3v18h18M7 16l4-4 4 4 5-6',
            'type' => DashboardWidgetType::StatGroup->value,
            'category' => 'sales',
            'width' => 12,
            'height' => 1,
            'display_order' => 10,
            'refresh_interval' => 300,
            'permission' => 'orders.view',
            'roles' => [],
            'is_active' => true,
        ],
        [
            'key' => 'order-stats',
            'name' => 'Order Pipeline',
            'description' => 'Live counts across every stage of the order lifecycle.',
            'icon' => 'M6 7h12l1.2 12.2a1.5 1.5 0 0 1-1.5 1.8H6.3a1.5 1.5 0 0 1-1.5-1.8L6 7Z',
            'type' => DashboardWidgetType::StatGroup->value,
            'category' => 'orders',
            'width' => 12,
            'height' => 1,
            'display_order' => 20,
            'refresh_interval' => 120,
            'permission' => 'orders.view',
            'roles' => [],
            'is_active' => true,
        ],
        [
            'key' => 'catalog-stats',
            'name' => 'Catalog Health',
            'description' => 'Products, brands, categories, and stock exposure at a glance.',
            'icon' => 'M16 3l5 3-2 5-2-1v10a1 1 0 0 1-1 1H8a1 1 0 0 1-1-1V10l-2 1-2-5 5-3a4 4 0 0 0 8 0Z',
            'type' => DashboardWidgetType::StatGroup->value,
            'category' => 'products',
            'width' => 12,
            'height' => 1,
            'display_order' => 30,
            'refresh_interval' => 600,
            'permission' => 'products.view',
            'roles' => [],
            'is_active' => true,
        ],
        [
            'key' => 'customer-stats',
            'name' => 'Customer Snapshot',
            'description' => 'New vs. active customers and newsletter reach for the range.',
            'icon' => 'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 7a4 4 0 1 0 0-8 4 4 0 0 0 0 8Z',
            'type' => DashboardWidgetType::StatGroup->value,
            'category' => 'customers',
            'width' => 12,
            'height' => 1,
            'display_order' => 40,
            'refresh_interval' => 600,
            'permission' => 'customers.view',
            'roles' => [],
            'is_active' => true,
        ],

        // ---- Charts --------------------------------------------------------
        [
            'key' => 'sales-trend',
            'name' => 'Sales Trend',
            'description' => 'Completed revenue over time for the selected range.',
            'icon' => 'M3 3v18h18M7 14l3-3 4 4 4-6',
            'type' => DashboardWidgetType::Chart->value,
            'category' => 'sales',
            'width' => 8,
            'height' => 2,
            'display_order' => 50,
            'refresh_interval' => 600,
            'permission' => 'orders.view',
            'roles' => [],
            'is_active' => true,
        ],
        [
            'key' => 'order-status-breakdown',
            'name' => 'Order Status Breakdown',
            'description' => 'Distribution of orders by status for the range.',
            'icon' => 'M12 2a10 10 0 1 0 10 10h-10Z',
            'type' => DashboardWidgetType::Chart->value,
            'category' => 'orders',
            'width' => 4,
            'height' => 2,
            'display_order' => 60,
            'refresh_interval' => 300,
            'permission' => 'orders.view',
            'roles' => [],
            'is_active' => true,
        ],
        [
            'key' => 'orders-trend',
            'name' => 'Orders Volume',
            'description' => 'Order counts over time for the selected range.',
            'icon' => 'M4 19V5m4 14V9m4 10V7m4 12v-6m4 6V4',
            'type' => DashboardWidgetType::Chart->value,
            'category' => 'orders',
            'width' => 6,
            'height' => 2,
            'display_order' => 70,
            'refresh_interval' => 600,
            'permission' => 'orders.view',
            'roles' => [],
            'is_active' => true,
        ],
        [
            'key' => 'top-categories',
            'name' => 'Top Categories',
            'description' => 'Best performing categories by completed revenue.',
            'icon' => 'M4 4h16v4H4zM4 10h10v10H4zM16 10h4v10h-4z',
            'type' => DashboardWidgetType::Chart->value,
            'category' => 'products',
            'width' => 6,
            'height' => 2,
            'display_order' => 80,
            'refresh_interval' => 900,
            'permission' => 'products.view',
            'roles' => [],
            'is_active' => true,
        ],
        [
            'key' => 'inventory-status',
            'name' => 'Inventory Status',
            'description' => 'In-stock, low-stock and out-of-stock product mix.',
            'icon' => 'M20 7 12 3 4 7m16 0-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4',
            'type' => DashboardWidgetType::Chart->value,
            'category' => 'inventory',
            'width' => 6,
            'height' => 2,
            'display_order' => 90,
            'refresh_interval' => 900,
            'permission' => 'inventory.view',
            'roles' => [],
            'is_active' => true,
        ],
        [
            'key' => 'customer-growth',
            'name' => 'Customer Growth',
            'description' => 'New customer registrations over time.',
            'icon' => 'M3 3v18h18M7 15l4-4 3 3 5-6',
            'type' => DashboardWidgetType::Chart->value,
            'category' => 'customers',
            'width' => 6,
            'height' => 2,
            'display_order' => 100,
            'refresh_interval' => 900,
            'permission' => 'customers.view',
            'roles' => [],
            'is_active' => true,
        ],

        // ---- Tables --------------------------------------------------------
        [
            'key' => 'recent-orders',
            'name' => 'Recent Orders',
            'description' => 'Latest orders placed within the selected range.',
            'icon' => 'M9 5H7a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-2M9 5a2 2 0 0 0 2 2h2a2 2 0 0 0 2-2M9 5a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2',
            'type' => DashboardWidgetType::Table->value,
            'category' => 'orders',
            'width' => 8,
            'height' => 3,
            'display_order' => 110,
            'refresh_interval' => 120,
            'permission' => 'orders.view',
            'roles' => [],
            'is_active' => true,
        ],
        [
            'key' => 'low-stock',
            'name' => 'Low Stock Alerts',
            'description' => 'Products at or below their low-stock threshold.',
            'icon' => 'M12 9v4m0 4h.01M10.29 3.86 1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0Z',
            'type' => DashboardWidgetType::Table->value,
            'category' => 'inventory',
            'width' => 4,
            'height' => 3,
            'display_order' => 120,
            'refresh_interval' => 300,
            'permission' => 'inventory.view',
            'roles' => [],
            'is_active' => true,
        ],
        [
            'key' => 'best-selling-products',
            'name' => 'Best Selling Products',
            'description' => 'Top products by units sold from completed orders.',
            'icon' => 'M5 3l14 9-14 9V3Z',
            'type' => DashboardWidgetType::Table->value,
            'category' => 'products',
            'width' => 6,
            'height' => 3,
            'display_order' => 130,
            'refresh_interval' => 600,
            'permission' => 'products.view',
            'roles' => [],
            'is_active' => true,
        ],
        [
            'key' => 'latest-customers',
            'name' => 'Latest Customers',
            'description' => 'Most recently registered customers.',
            'icon' => 'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 7a4 4 0 1 0 0-8 4 4 0 0 0 0 8Z',
            'type' => DashboardWidgetType::Table->value,
            'category' => 'customers',
            'width' => 6,
            'height' => 3,
            'display_order' => 140,
            'refresh_interval' => 300,
            'permission' => 'customers.view',
            'roles' => [],
            'is_active' => true,
        ],
        [
            'key' => 'top-customers',
            'name' => 'Top Customers',
            'description' => 'Highest spending customers from completed orders.',
            'icon' => 'M12 2l2.4 7.4H22l-6 4.6 2.3 7-6.3-4.6L5.7 21 8 14 2 9.4h7.6L12 2Z',
            'type' => DashboardWidgetType::Table->value,
            'category' => 'customers',
            'width' => 6,
            'height' => 3,
            'display_order' => 150,
            'refresh_interval' => 900,
            'permission' => 'customers.view',
            'roles' => [],
            'is_active' => true,
        ],
        [
            'key' => 'latest-reviews',
            'name' => 'Latest Reviews',
            'description' => 'Most recent product reviews awaiting or granted approval.',
            'icon' => 'M12 2l2.4 7.4H22l-6 4.6 2.3 7-6.3-4.6L5.7 21 8 14 2 9.4h7.6L12 2Z',
            'type' => DashboardWidgetType::Table->value,
            'category' => 'products',
            'width' => 6,
            'height' => 3,
            'display_order' => 160,
            'refresh_interval' => 600,
            'permission' => 'products.view',
            'roles' => [],
            'is_active' => true,
        ],

        // ---- Activity / notifications / quick actions ----------------------
        [
            'key' => 'activity-timeline',
            'name' => 'Activity Timeline',
            'description' => 'Recent system and business events from the audit log.',
            'icon' => 'M12 8v4l3 3M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18Z',
            'type' => DashboardWidgetType::Timeline->value,
            'category' => 'activity',
            'width' => 6,
            'height' => 3,
            'display_order' => 170,
            'refresh_interval' => 120,
            'permission' => 'audit.view',
            'roles' => [],
            'is_active' => true,
        ],
        [
            'key' => 'notifications',
            'name' => 'Notifications',
            'description' => 'Your unread alerts — low stock, pending orders, and system messages.',
            'icon' => 'M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9M10.3 21a1.94 1.94 0 0 0 3.4 0',
            'type' => DashboardWidgetType::Notifications->value,
            'category' => 'activity',
            'width' => 6,
            'height' => 3,
            'display_order' => 180,
            'refresh_interval' => 60,
            'permission' => 'notifications.view',
            'roles' => [],
            'is_active' => true,
        ],
        [
            'key' => 'quick-actions',
            'name' => 'Quick Actions',
            'description' => 'One-click shortcuts to the tasks you use most.',
            'icon' => 'M13 2 3 14h7l-1 8 10-12h-7l1-8Z',
            'type' => DashboardWidgetType::QuickActions->value,
            'category' => 'system',
            'width' => 12,
            'height' => 1,
            'display_order' => 190,
            'refresh_interval' => null,
            'permission' => null,
            'roles' => [],
            'is_active' => true,
        ],

        // ---- Marketing -----------------------------------------------------
        [
            'key' => 'marketing-calendar',
            'name' => 'Marketing Calendar',
            'description' => 'Scheduled offers, promotions, and campaign windows.',
            'icon' => 'M8 2v4M16 2v4M3 10h18M5 4h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z',
            'type' => DashboardWidgetType::Calendar->value,
            'category' => 'marketing',
            'width' => 6,
            'height' => 3,
            'display_order' => 200,
            'refresh_interval' => 900,
            'permission' => 'offers.view',
            'roles' => [],
            'is_active' => true,
        ],

        // ---- Business map (future-ready) -----------------------------------
        [
            'key' => 'orders-by-region',
            'name' => 'Orders by Region',
            'description' => 'Geographic distribution of orders. Future-ready for district maps.',
            'icon' => 'M9 20 3 17V4l6 3 6-3 6 3v13l-6 3-6-3-6 3M9 7v13M15 4v13',
            'type' => DashboardWidgetType::Map->value,
            'category' => 'sales',
            'width' => 6,
            'height' => 3,
            'display_order' => 210,
            'refresh_interval' => 900,
            'permission' => 'orders.view',
            'roles' => [],
            'is_active' => true,
        ],

        // ---- Announcements / weather (optional) ----------------------------
        [
            'key' => 'announcements',
            'name' => 'Announcements',
            'description' => 'Company announcements, release notes, and maintenance windows.',
            'icon' => 'M3 11v2a1 1 0 0 0 1 1h3l4 4V6L7 10H4a1 1 0 0 0-1 1ZM16 8a5 5 0 0 1 0 8',
            'type' => DashboardWidgetType::Announcement->value,
            'category' => 'system',
            'width' => 6,
            'height' => 2,
            'display_order' => 220,
            'refresh_interval' => null,
            'permission' => null,
            'roles' => [],
            'is_active' => true,
        ],
        [
            'key' => 'weather',
            'name' => 'Weather',
            'description' => 'Local weather for delivery planning. Optional — disabled by default.',
            'icon' => 'M17 18a5 5 0 0 0-10 0M12 2v2M4.9 6.3l1.4 1.4M2 13h2M20 13h2M17.7 7.7l1.4-1.4M7 18a5 5 0 0 1 10 0',
            'type' => DashboardWidgetType::Weather->value,
            'category' => 'system',
            'width' => 4,
            'height' => 2,
            'display_order' => 230,
            'refresh_interval' => 1800,
            'permission' => null,
            'roles' => [],
            'is_active' => false,
        ],
    ],
];
